name:                hanalytics-agent
version:             0.1.0.0
github:              "petereast/hanalytics-agent"
license:             BSD3
author:              "Peter East"
maintainer:          "petereast+github@pm.me"
copyright:           "2019 Peter East"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hanalytics-agent#readme>

dependencies:
- base >= 4.7 && < 5
- hedis >= 0.10.0
- bytestring >= 0.10.8.2
- aeson >= 1.4.2.0
- snap-core >= 0.9
- snap-server >= 0.9
- time >= 1.8.0.2

library:
  source-dirs: src

executables:
  hanalytics-agent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanalytics-agent

tests:
  hanalytics-agent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanalytics-agent
